import { Team, Match, UserProfile, League, Standing, Prediction } from '../types/domain';

// 48 qualified teams (FIFA World Cup 2026 draw)
export const TEAMS: Record<string, Team> = {
  USA: { code: 'USA', name: 'Estados Unidos',       hue: 222 },
  MEX: { code: 'MEX', name: 'México',               hue: 142 },
  CAN: { code: 'CAN', name: 'Canadá',               hue: 0   },
  PAN: { code: 'PAN', name: 'Panamá',               hue: 350 },
  ARG: { code: 'ARG', name: 'Argentina',            hue: 205 },
  BRA: { code: 'BRA', name: 'Brasil',               hue: 52  },
  COL: { code: 'COL', name: 'Colombia',             hue: 48  },
  URU: { code: 'URU', name: 'Uruguay',              hue: 200 },
  ECU: { code: 'ECU', name: 'Ecuador',              hue: 45  },
  PAR: { code: 'PAR', name: 'Paraguay',             hue: 200 },
  FRA: { code: 'FRA', name: 'Francia',              hue: 230 },
  ESP: { code: 'ESP', name: 'España',               hue: 8   },
  GER: { code: 'GER', name: 'Alemania',             hue: 50  },
  ENG: { code: 'ENG', name: 'Inglaterra',           hue: 220 },
  POR: { code: 'POR', name: 'Portugal',             hue: 142 },
  NED: { code: 'NED', name: 'Países Bajos',         hue: 30  },
  BEL: { code: 'BEL', name: 'Bélgica',             hue: 0   },
  CRO: { code: 'CRO', name: 'Croacia',             hue: 350 },
  SUI: { code: 'SUI', name: 'Suiza',               hue: 0   },
  AUT: { code: 'AUT', name: 'Austria',             hue: 4   },
  SCO: { code: 'SCO', name: 'Escocia',             hue: 210 },
  TUR: { code: 'TUR', name: 'Türkiye',             hue: 15  },
  SWE: { code: 'SWE', name: 'Suecia',              hue: 50  },
  NOR: { code: 'NOR', name: 'Noruega',             hue: 5   },
  CZE: { code: 'CZE', name: 'Chequia',             hue: 0   },
  BIH: { code: 'BIH', name: 'Bosnia y Herzeg.',    hue: 205 },
  MAR: { code: 'MAR', name: 'Marruecos',           hue: 350 },
  SEN: { code: 'SEN', name: 'Senegal',             hue: 150 },
  EGY: { code: 'EGY', name: 'Egipto',             hue: 5   },
  CIV: { code: 'CIV', name: 'Costa de Marfil',    hue: 28  },
  ALG: { code: 'ALG', name: 'Argelia',            hue: 145 },
  TUN: { code: 'TUN', name: 'Túnez',              hue: 10  },
  RSA: { code: 'RSA', name: 'Sudáfrica',          hue: 130 },
  GHA: { code: 'GHA', name: 'Ghana',              hue: 50  },
  COD: { code: 'COD', name: 'Congo DR',           hue: 210 },
  JPN: { code: 'JPN', name: 'Japón',              hue: 0   },
  KOR: { code: 'KOR', name: 'Corea del Sur',      hue: 0   },
  IRI: { code: 'IRI', name: 'Irán',               hue: 142 },
  KSA: { code: 'KSA', name: 'Arabia Saudita',     hue: 135 },
  AUS: { code: 'AUS', name: 'Australia',          hue: 50  },
  IRQ: { code: 'IRQ', name: 'Irak',               hue: 90  },
  UZB: { code: 'UZB', name: 'Uzbekistán',         hue: 168 },
  QAT: { code: 'QAT', name: 'Qatar',              hue: 320 },
  JOR: { code: 'JOR', name: 'Jordania',           hue: 350 },
  NZL: { code: 'NZL', name: 'Nueva Zelanda',      hue: 225 },
  HAI: { code: 'HAI', name: 'Haití',              hue: 210 },
  CPV: { code: 'CPV', name: 'Cabo Verde',          hue: 160 },
  CUR: { code: 'CUR', name: 'Curazao',            hue: 210 },
};

// Phases display helper
export const PHASES = {
  groups: { label: 'Grupos', color: 'bg-blue-600/20 text-blue-400 border-blue-500/30' },
  r32: { label: '1/32 Final', color: 'bg-purple-600/20 text-purple-400 border-purple-500/30' },
  r16: { label: '1/16 Final', color: 'bg-orange-600/20 text-orange-400 border-orange-500/30' },
  quarters: { label: 'Cuartos', color: 'bg-green-600/20 text-green-400 border-green-500/30' },
  semis: { label: 'Semis', color: 'bg-red-600/20 text-red-400 border-red-500/30' },
  final: { label: 'Final', color: 'bg-amber-600/20 text-amber-400 border-amber-500/30' },
};

// Mock Logged In User
export const MOCK_USER: UserProfile = {
  id: 'u-1',
  name: 'Gustavo',
  displayName: 'Gus_Hipolito',
  email: 'gustavo@example.com',
  avatarUrl: undefined,
  whatsapp: '+573000000000',
  isSuperadmin: true,
  createdAt: '2026-05-01T12:00:00Z',
};

// Mock Leagues
export const MOCK_LEAGUES: League[] = [
  {
    id: 'l-1',
    name: 'Los Hipólitos F.C.',
    slug: 'los-hipolitos-fc',
    inviteCode: 'HIPO2026',
    pot: 1500,
    status: 'active',
    createdAt: '2026-05-10T14:30:00Z',
  },
  {
    id: 'l-2',
    name: 'Oficina Central',
    slug: 'oficina-central',
    inviteCode: 'WORK2026',
    pot: 450,
    status: 'active',
    createdAt: '2026-05-15T09:00:00Z',
  },
];

// Mock Matches
export const MOCK_MATCHES: Match[] = [
  {
    id: 'm-1',
    phase: 'groups',
    group: 'A',
    jornada: 'Fecha 1',
    homeTeamCode: 'MEX',
    awayTeamCode: 'CAN',
    homeScore: 2,
    awayScore: 1,
    kickoffUtc: '2026-06-11T17:00:00Z', // Past match
    status: 'result',
    venue: 'Estadio Azteca',
    city: 'Ciudad de México',
  },
  {
    id: 'm-2',
    phase: 'groups',
    group: 'A',
    jornada: 'Fecha 1',
    homeTeamCode: 'USA',
    awayTeamCode: 'PAN',
    homeScore: 1,
    awayScore: 1,
    kickoffUtc: '2026-06-12T04:30:00Z', // Currently live in mock timeline
    status: 'live',
    venue: 'SoFi Stadium',
    city: 'Los Ángeles',
  },
  {
    id: 'm-3',
    phase: 'groups',
    group: 'B',
    jornada: 'Fecha 1',
    homeTeamCode: 'ARG',
    awayTeamCode: 'COL',
    homeScore: null,
    awayScore: null,
    kickoffUtc: '2026-06-12T22:00:00Z', // Soon
    status: 'soon',
    venue: 'MetLife Stadium',
    city: 'Nueva York',
  },
  {
    id: 'm-4',
    phase: 'groups',
    group: 'C',
    jornada: 'Fecha 1',
    homeTeamCode: 'BRA',
    awayTeamCode: 'URU',
    homeScore: null,
    awayScore: null,
    kickoffUtc: '2026-06-13T18:00:00Z', // Open
    status: 'open',
    venue: 'AT&T Stadium',
    city: 'Dallas',
  },
  {
    id: 'm-5',
    phase: 'groups',
    group: 'D',
    jornada: 'Fecha 1',
    homeTeamCode: 'FRA',
    awayTeamCode: 'GER',
    homeScore: null,
    awayScore: null,
    kickoffUtc: '2026-06-14T20:00:00Z', // Open (unpredicted)
    status: 'open',
    venue: 'BC Place',
    city: 'Vancouver',
  },
];

// Mock Predictions for MOCK_USER (u-1)
export const MOCK_PREDICTIONS: Record<string, Prediction> = {
  'm-1': {
    id: 'p-1',
    userId: 'u-1',
    matchId: 'm-1',
    homePrediction: 2,
    awayPrediction: 1,
    pointsEarned: 5,
    scoreType: 'exact',
    updatedAt: '2026-06-11T16:00:00Z',
  },
  'm-2': {
    id: 'p-2',
    userId: 'u-1',
    matchId: 'm-2',
    homePrediction: 2,
    awayPrediction: 1, // live prediction (currently 1-1, predicting 2-1)
    pointsEarned: null,
    scoreType: null,
    updatedAt: '2026-06-12T04:00:00Z',
  },
  'm-3': {
    id: 'p-3',
    userId: 'u-1',
    matchId: 'm-3',
    homePrediction: 1,
    awayPrediction: 0, // soon prediction (locked)
    pointsEarned: null,
    scoreType: null,
    updatedAt: '2026-06-12T04:10:00Z',
  },
  'm-4': {
    id: 'p-4',
    userId: 'u-1',
    matchId: 'm-4',
    homePrediction: 3,
    awayPrediction: 2, // open prediction (editable)
    pointsEarned: null,
    scoreType: null,
    updatedAt: '2026-06-12T04:15:00Z',
  },
};

// Mock League Leaderboard Standings for League 'l-1'
export const MOCK_STANDINGS: Standing[] = [
  {
    leagueId: 'l-1',
    userId: 'u-2',
    displayName: 'Carlos_CR7',
    avatarUrl: undefined,
    points: 12,
    exacts: 2,
    tendencies: 0,
    consolations: 2,
    misses: 0,
    rank: 1,
    previousRank: 2,
  },
  {
    leagueId: 'l-1',
    userId: 'u-1',
    displayName: 'Gus_Hipolito',
    points: 10,
    exacts: 1,
    tendencies: 1,
    consolations: 2,
    misses: 1,
    rank: 2,
    previousRank: 1,
  },
  {
    leagueId: 'l-1',
    userId: 'u-3',
    displayName: 'Mariana_10',
    avatarUrl: undefined,
    points: 8,
    exacts: 1,
    tendencies: 1,
    consolations: 0,
    misses: 3,
    rank: 3,
    previousRank: 3,
  },
  {
    leagueId: 'l-1',
    userId: 'u-4',
    displayName: 'El_Profe',
    avatarUrl: undefined,
    points: 5,
    exacts: 0,
    tendencies: 1,
    consolations: 2,
    misses: 2,
    rank: 4,
    previousRank: 5,
  },
  {
    leagueId: 'l-1',
    userId: 'u-5',
    displayName: 'Beto_Rojas',
    avatarUrl: undefined,
    points: 3,
    exacts: 0,
    tendencies: 1,
    consolations: 0,
    misses: 4,
    rank: 5,
    previousRank: 4,
  },
];
